CREATE TABLE client (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(200) NOT NULL
);

CREATE TABLE planet (
                        id VARCHAR(20) PRIMARY KEY,
                        name VARCHAR(500) NOT NULL
);

CREATE TABLE ticket (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        created_at TIMESTAMP NOT NULL,
                        client_id BIGINT NOT NULL,
                        from_planet_id VARCHAR(20) NOT NULL,
                        to_planet_id VARCHAR(20) NOT NULL,

                        CONSTRAINT fk_ticket_client FOREIGN KEY (client_id) REFERENCES client(id),
                        CONSTRAINT fk_ticket_from FOREIGN KEY (from_planet_id) REFERENCES planet(id),
                        CONSTRAINT fk_ticket_to FOREIGN KEY (to_planet_id) REFERENCES planet(id)
);